language: python
python:
        - '3.8'

before_script:
        - pip install -r requirements.txt

branches:
        only:
            - staging

env: DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

services:
        - postgresql

script:
        - ./manage.py test